### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by HappiePlant** [Vanilla-OS/legendary-desktop-feedback#11]
This project is currently written in LANGUAGE NAME which is a very slow language and a pain to work with. This project should be rewritten in Rust for memory safety and better performance.

**Comment by pietrodicaprio** [comment]
C#, using .Net Core, is absolutely not slow and memory management is not an issue since we follow proper coding paradigms and best practices.
A rewrite in Rust is a big NO.

**Comment by HappiePlant** [comment]
C# is a language made by Microsoft. Using it is a sin against the open source community. This project needs to be rewritten to Rust ASAP.

**Comment by pietrodicaprio** [comment]
Well: https://github.com/dotnet

Please keep up to date with Microsoft's changes and willing to contribute to OSS. A rewrite in Rust will never happen.
