### ISSUE TITLE
Fixed size search

### ISSUE THREAD

**Issue by tulilirockz** [Vanilla-OS/legendary-desktop-feedback#8]
Maybe the search should be fixed size instead of changing sizes depending on the search queries, since that may confuse some people and honestly it looks a bit weird IMO! 

Anyways, amazing work on this DE! I hope the best for all of you!

**Comment by mirkobrombin** [comment]
Mmh yes you are right!

**Comment by tulilirockz** [comment]
bro.... literally just now figured out this was an april 1st joke...

**Comment by mirkobrombin** [comment]
Is it? :eyes:

**Comment by tulilirockz** [comment]
i hope not! seems like a cool idea honestly, still, i literally just now saw the "april 1st" date on the comments n everything else....
